/*
 * generated by Xtext 2.21.0
 */
package de.joneug.mdal.ide;

import org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider;
import org.eclipse.xtext.ide.server.codeActions.ICodeActionService2;
import org.eclipse.xtext.ide.server.commands.IExecutableCommandService;

import de.joneug.mdal.ide.action.MdalCodeActionService;
import de.joneug.mdal.ide.command.MdalCommandService;
import de.joneug.mdal.ide.contentassist.MdalContentProposalProvider;

/**
 * Use this class to register ide components.
 */
public class MdalIdeModule extends AbstractMdalIdeModule {
	
	public Class<? extends IExecutableCommandService> bindIExecutableCommandService() {
		return MdalCommandService.class;
	}
	
	public Class<? extends ICodeActionService2> bindICodeActionService2() {
		return MdalCodeActionService.class;
	}
	
	public Class<? extends IdeContentProposalProvider> bindIdeContentProposalProvider() {
		return MdalContentProposalProvider.class;
	}
		
}
