/*
 * generated by Xtext 2.21.0
 */
package de.joneug.mdal.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.joneug.mdal.MdalRuntimeModule;
import de.joneug.mdal.MdalStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MdalIdeSetup extends MdalStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MdalRuntimeModule(), new MdalIdeModule()));
	}
	
}
