/*
 * generated by Xtext 2.21.0
 */
package de.joneug.tests

import com.google.inject.Inject
import de.joneug.mdal.Model
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.eclipse.xtext.util.EmfFormatter
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(MdalInjectorProvider)
class MdalParsingTest {
	
	@Inject
	ParseHelper<Model> parseHelper
	
	@Test
	def void loadModel() {
		val model = parseHelper.parse('''
			extension 'Seminar Module' {
				idRanges: [
					50000,
					50000..100000
				]
			}
		''')

		println(EmfFormatter.objToStr(model))

		Assert.assertNotNull(model)
		val errors = model.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
