/*
 * generated by Xtext 2.21.0
 */
package de.joneug.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class MdalScopeProvider extends AbstractMdalScopeProvider {

}
