/*
 * generated by Xtext 2.21.0
 */
package de.joneug.mdal.parser.antlr;

import com.google.inject.Inject;
import de.joneug.mdal.parser.antlr.internal.InternalMdalParser;
import de.joneug.mdal.services.MdalGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MdalParser extends AbstractAntlrParser {

	@Inject
	private MdalGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMdalParser createParser(XtextTokenStream stream) {
		return new InternalMdalParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MdalGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MdalGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
