/*
 * generated by Xtext 2.21.0
 */
package de.joneug.mdal.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMdalScopeProvider extends DelegatingScopeProvider {
}
