/*
 * generated by Xtext 2.21.0
 */
package de.joneug.mdal;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MdalRuntimeModule extends AbstractMdalRuntimeModule {
}
