/*
 * generated by Xtext 2.21.0
 */
package de.joneug.mdal;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MdalStandaloneSetup extends MdalStandaloneSetupGenerated {

	public static void doSetup() {
		new MdalStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
