/*
 * generated by Xtext 2.21.0
 */
package de.joneug.mdal.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMdalValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(de.joneug.mdal.mdal.MdalPackage.eINSTANCE);
		return result;
	}
}
