/*
 * generated by Xtext 2.21.0
 */
package de.joneug.mdal.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MdalGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.joneug.mdal.Mdal.Model");
		private final Assignment cAlExtensionsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cAlExtensionsAlExtensionParserRuleCall_0 = (RuleCall)cAlExtensionsAssignment.eContents().get(0);
		
		//Model:
		//	alExtensions+=AlExtension*;
		@Override public ParserRule getRule() { return rule; }
		
		//alExtensions+=AlExtension*
		public Assignment getAlExtensionsAssignment() { return cAlExtensionsAssignment; }
		
		//AlExtension
		public RuleCall getAlExtensionsAlExtensionParserRuleCall_0() { return cAlExtensionsAlExtensionParserRuleCall_0; }
	}
	public class AlExtensionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.joneug.mdal.Mdal.AlExtension");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cExtensionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cIdKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cIdAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cIdSTRINGTerminalRuleCall_3_1_0 = (RuleCall)cIdAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cIdRangesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Group cGroup_4_2 = (Group)cGroup_4.eContents().get(2);
		private final Assignment cIdRangesAssignment_4_2_0 = (Assignment)cGroup_4_2.eContents().get(0);
		private final RuleCall cIdRangesIdRangeParserRuleCall_4_2_0_0 = (RuleCall)cIdRangesAssignment_4_2_0.eContents().get(0);
		private final Group cGroup_4_2_1 = (Group)cGroup_4_2.eContents().get(1);
		private final Keyword cCommaKeyword_4_2_1_0 = (Keyword)cGroup_4_2_1.eContents().get(0);
		private final Assignment cIdRangesAssignment_4_2_1_1 = (Assignment)cGroup_4_2_1.eContents().get(1);
		private final RuleCall cIdRangesIdRangeParserRuleCall_4_2_1_1_0 = (RuleCall)cIdRangesAssignment_4_2_1_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_4_3 = (Keyword)cGroup_4.eContents().get(3);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPlatformKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPlatformAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPlatformSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cPlatformAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPublisherKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cPublisherAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cPublisherSTRINGTerminalRuleCall_6_1_0 = (RuleCall)cPublisherAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cVersionKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cVersionAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cVersionSTRINGTerminalRuleCall_7_1_0 = (RuleCall)cVersionAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cBriefKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cBriefAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cBriefSTRINGTerminalRuleCall_8_1_0 = (RuleCall)cBriefAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cDescriptionKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cDescriptionAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_9_1_0 = (RuleCall)cDescriptionAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cPrivacyStatementKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cPrivacyStatementAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cPrivacyStatementSTRINGTerminalRuleCall_10_1_0 = (RuleCall)cPrivacyStatementAssignment_10_1.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cEulaKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cEulaAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cEulaSTRINGTerminalRuleCall_11_1_0 = (RuleCall)cEulaAssignment_11_1.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cHelpKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cHelpAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cHelpSTRINGTerminalRuleCall_12_1_0 = (RuleCall)cHelpAssignment_12_1.eContents().get(0);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cUrlKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Assignment cUrlAssignment_13_1 = (Assignment)cGroup_13.eContents().get(1);
		private final RuleCall cUrlSTRINGTerminalRuleCall_13_1_0 = (RuleCall)cUrlAssignment_13_1.eContents().get(0);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cContextSensitiveHelpUrlKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Assignment cContextSensitiveHelpUrlAssignment_14_1 = (Assignment)cGroup_14.eContents().get(1);
		private final RuleCall cContextSensitiveHelpUrlSTRINGTerminalRuleCall_14_1_0 = (RuleCall)cContextSensitiveHelpUrlAssignment_14_1.eContents().get(0);
		private final Group cGroup_15 = (Group)cGroup.eContents().get(15);
		private final Keyword cShowMyCodeKeyword_15_0 = (Keyword)cGroup_15.eContents().get(0);
		private final Assignment cShowMyCodeAssignment_15_1 = (Assignment)cGroup_15.eContents().get(1);
		private final RuleCall cShowMyCodeBoolEnumRuleCall_15_1_0 = (RuleCall)cShowMyCodeAssignment_15_1.eContents().get(0);
		private final Group cGroup_16 = (Group)cGroup.eContents().get(16);
		private final Keyword cRuntimeKeyword_16_0 = (Keyword)cGroup_16.eContents().get(0);
		private final Assignment cRuntimeAssignment_16_1 = (Assignment)cGroup_16.eContents().get(1);
		private final RuleCall cRuntimeSTRINGTerminalRuleCall_16_1_0 = (RuleCall)cRuntimeAssignment_16_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_17 = (Keyword)cGroup.eContents().get(17);
		
		//AlExtension:
		//	'extension' name=STRING '{' ('id' id=STRING)? ('idRanges' '[' (idRanges+=IdRange (',' idRanges+=IdRange)*) ']')?
		//	('platform' platform=STRING)? ('publisher' publisher=STRING)? ('version' version=STRING)? ('brief' brief=STRING)?
		//	('description' description=STRING)? ('privacyStatement' privacyStatement=STRING)? ('eula' eula=STRING)? ('help'
		//	help=STRING)? ('url' url=STRING)? ('contextSensitiveHelpUrl' contextSensitiveHelpUrl=STRING)? ('showMyCode'
		//	showMyCode=Bool)? ('runtime' runtime=STRING)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'extension' name=STRING '{' ('id' id=STRING)? ('idRanges' '[' (idRanges+=IdRange (',' idRanges+=IdRange)*) ']')?
		//('platform' platform=STRING)? ('publisher' publisher=STRING)? ('version' version=STRING)? ('brief' brief=STRING)?
		//('description' description=STRING)? ('privacyStatement' privacyStatement=STRING)? ('eula' eula=STRING)? ('help'
		//help=STRING)? ('url' url=STRING)? ('contextSensitiveHelpUrl' contextSensitiveHelpUrl=STRING)? ('showMyCode'
		//showMyCode=Bool)? ('runtime' runtime=STRING)? '}'
		public Group getGroup() { return cGroup; }
		
		//'extension'
		public Keyword getExtensionKeyword_0() { return cExtensionKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('id' id=STRING)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'id'
		public Keyword getIdKeyword_3_0() { return cIdKeyword_3_0; }
		
		//id=STRING
		public Assignment getIdAssignment_3_1() { return cIdAssignment_3_1; }
		
		//STRING
		public RuleCall getIdSTRINGTerminalRuleCall_3_1_0() { return cIdSTRINGTerminalRuleCall_3_1_0; }
		
		//('idRanges' '[' (idRanges+=IdRange (',' idRanges+=IdRange)*) ']')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'idRanges'
		public Keyword getIdRangesKeyword_4_0() { return cIdRangesKeyword_4_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_4_1() { return cLeftSquareBracketKeyword_4_1; }
		
		//(idRanges+=IdRange (',' idRanges+=IdRange)*)
		public Group getGroup_4_2() { return cGroup_4_2; }
		
		//idRanges+=IdRange
		public Assignment getIdRangesAssignment_4_2_0() { return cIdRangesAssignment_4_2_0; }
		
		//IdRange
		public RuleCall getIdRangesIdRangeParserRuleCall_4_2_0_0() { return cIdRangesIdRangeParserRuleCall_4_2_0_0; }
		
		//(',' idRanges+=IdRange)*
		public Group getGroup_4_2_1() { return cGroup_4_2_1; }
		
		//','
		public Keyword getCommaKeyword_4_2_1_0() { return cCommaKeyword_4_2_1_0; }
		
		//idRanges+=IdRange
		public Assignment getIdRangesAssignment_4_2_1_1() { return cIdRangesAssignment_4_2_1_1; }
		
		//IdRange
		public RuleCall getIdRangesIdRangeParserRuleCall_4_2_1_1_0() { return cIdRangesIdRangeParserRuleCall_4_2_1_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_4_3() { return cRightSquareBracketKeyword_4_3; }
		
		//('platform' platform=STRING)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'platform'
		public Keyword getPlatformKeyword_5_0() { return cPlatformKeyword_5_0; }
		
		//platform=STRING
		public Assignment getPlatformAssignment_5_1() { return cPlatformAssignment_5_1; }
		
		//STRING
		public RuleCall getPlatformSTRINGTerminalRuleCall_5_1_0() { return cPlatformSTRINGTerminalRuleCall_5_1_0; }
		
		//('publisher' publisher=STRING)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'publisher'
		public Keyword getPublisherKeyword_6_0() { return cPublisherKeyword_6_0; }
		
		//publisher=STRING
		public Assignment getPublisherAssignment_6_1() { return cPublisherAssignment_6_1; }
		
		//STRING
		public RuleCall getPublisherSTRINGTerminalRuleCall_6_1_0() { return cPublisherSTRINGTerminalRuleCall_6_1_0; }
		
		//('version' version=STRING)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'version'
		public Keyword getVersionKeyword_7_0() { return cVersionKeyword_7_0; }
		
		//version=STRING
		public Assignment getVersionAssignment_7_1() { return cVersionAssignment_7_1; }
		
		//STRING
		public RuleCall getVersionSTRINGTerminalRuleCall_7_1_0() { return cVersionSTRINGTerminalRuleCall_7_1_0; }
		
		//('brief' brief=STRING)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'brief'
		public Keyword getBriefKeyword_8_0() { return cBriefKeyword_8_0; }
		
		//brief=STRING
		public Assignment getBriefAssignment_8_1() { return cBriefAssignment_8_1; }
		
		//STRING
		public RuleCall getBriefSTRINGTerminalRuleCall_8_1_0() { return cBriefSTRINGTerminalRuleCall_8_1_0; }
		
		//('description' description=STRING)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'description'
		public Keyword getDescriptionKeyword_9_0() { return cDescriptionKeyword_9_0; }
		
		//description=STRING
		public Assignment getDescriptionAssignment_9_1() { return cDescriptionAssignment_9_1; }
		
		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_9_1_0() { return cDescriptionSTRINGTerminalRuleCall_9_1_0; }
		
		//('privacyStatement' privacyStatement=STRING)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'privacyStatement'
		public Keyword getPrivacyStatementKeyword_10_0() { return cPrivacyStatementKeyword_10_0; }
		
		//privacyStatement=STRING
		public Assignment getPrivacyStatementAssignment_10_1() { return cPrivacyStatementAssignment_10_1; }
		
		//STRING
		public RuleCall getPrivacyStatementSTRINGTerminalRuleCall_10_1_0() { return cPrivacyStatementSTRINGTerminalRuleCall_10_1_0; }
		
		//('eula' eula=STRING)?
		public Group getGroup_11() { return cGroup_11; }
		
		//'eula'
		public Keyword getEulaKeyword_11_0() { return cEulaKeyword_11_0; }
		
		//eula=STRING
		public Assignment getEulaAssignment_11_1() { return cEulaAssignment_11_1; }
		
		//STRING
		public RuleCall getEulaSTRINGTerminalRuleCall_11_1_0() { return cEulaSTRINGTerminalRuleCall_11_1_0; }
		
		//('help' help=STRING)?
		public Group getGroup_12() { return cGroup_12; }
		
		//'help'
		public Keyword getHelpKeyword_12_0() { return cHelpKeyword_12_0; }
		
		//help=STRING
		public Assignment getHelpAssignment_12_1() { return cHelpAssignment_12_1; }
		
		//STRING
		public RuleCall getHelpSTRINGTerminalRuleCall_12_1_0() { return cHelpSTRINGTerminalRuleCall_12_1_0; }
		
		//('url' url=STRING)?
		public Group getGroup_13() { return cGroup_13; }
		
		//'url'
		public Keyword getUrlKeyword_13_0() { return cUrlKeyword_13_0; }
		
		//url=STRING
		public Assignment getUrlAssignment_13_1() { return cUrlAssignment_13_1; }
		
		//STRING
		public RuleCall getUrlSTRINGTerminalRuleCall_13_1_0() { return cUrlSTRINGTerminalRuleCall_13_1_0; }
		
		//('contextSensitiveHelpUrl' contextSensitiveHelpUrl=STRING)?
		public Group getGroup_14() { return cGroup_14; }
		
		//'contextSensitiveHelpUrl'
		public Keyword getContextSensitiveHelpUrlKeyword_14_0() { return cContextSensitiveHelpUrlKeyword_14_0; }
		
		//contextSensitiveHelpUrl=STRING
		public Assignment getContextSensitiveHelpUrlAssignment_14_1() { return cContextSensitiveHelpUrlAssignment_14_1; }
		
		//STRING
		public RuleCall getContextSensitiveHelpUrlSTRINGTerminalRuleCall_14_1_0() { return cContextSensitiveHelpUrlSTRINGTerminalRuleCall_14_1_0; }
		
		//('showMyCode' showMyCode=Bool)?
		public Group getGroup_15() { return cGroup_15; }
		
		//'showMyCode'
		public Keyword getShowMyCodeKeyword_15_0() { return cShowMyCodeKeyword_15_0; }
		
		//showMyCode=Bool
		public Assignment getShowMyCodeAssignment_15_1() { return cShowMyCodeAssignment_15_1; }
		
		//Bool
		public RuleCall getShowMyCodeBoolEnumRuleCall_15_1_0() { return cShowMyCodeBoolEnumRuleCall_15_1_0; }
		
		//('runtime' runtime=STRING)?
		public Group getGroup_16() { return cGroup_16; }
		
		//'runtime'
		public Keyword getRuntimeKeyword_16_0() { return cRuntimeKeyword_16_0; }
		
		//runtime=STRING
		public Assignment getRuntimeAssignment_16_1() { return cRuntimeAssignment_16_1; }
		
		//STRING
		public RuleCall getRuntimeSTRINGTerminalRuleCall_16_1_0() { return cRuntimeSTRINGTerminalRuleCall_16_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_17() { return cRightCurlyBracketKeyword_17; }
	}
	public class DocumentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.joneug.mdal.Mdal.Document");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDocumentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Document:
		//	'document' name=STRING '{'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'document' name=STRING '{' '}'
		public Group getGroup() { return cGroup; }
		
		//'document'
		public Keyword getDocumentKeyword_0() { return cDocumentKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class FieldElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.joneug.mdal.Mdal.Field");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFieldKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNoKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNoAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNoINTTerminalRuleCall_3_1_0 = (RuleCall)cNoAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Keyword cTypeKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTypeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTypeTypeParserRuleCall_6_0 = (RuleCall)cTypeAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Field:
		//	'field' name=STRING '{' ('no' no=INT)? ('description' description=STRING)?
		//	'type' type=Type
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'field' name=STRING '{' ('no' no=INT)? ('description' description=STRING)? 'type' type=Type '}'
		public Group getGroup() { return cGroup; }
		
		//'field'
		public Keyword getFieldKeyword_0() { return cFieldKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('no' no=INT)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'no'
		public Keyword getNoKeyword_3_0() { return cNoKeyword_3_0; }
		
		//no=INT
		public Assignment getNoAssignment_3_1() { return cNoAssignment_3_1; }
		
		//INT
		public RuleCall getNoINTTerminalRuleCall_3_1_0() { return cNoINTTerminalRuleCall_3_1_0; }
		
		//('description' description=STRING)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'description'
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }
		
		//description=STRING
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }
		
		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_4_1_0() { return cDescriptionSTRINGTerminalRuleCall_4_1_0; }
		
		//'type'
		public Keyword getTypeKeyword_5() { return cTypeKeyword_5; }
		
		//type=Type
		public Assignment getTypeAssignment_6() { return cTypeAssignment_6; }
		
		//Type
		public RuleCall getTypeTypeParserRuleCall_6_0() { return cTypeTypeParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.joneug.mdal.Mdal.Type");
		private final RuleCall cTypeTextParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Type:
		//	TypeText;
		@Override public ParserRule getRule() { return rule; }
		
		//TypeText
		public RuleCall getTypeTextParserRuleCall() { return cTypeTextParserRuleCall; }
	}
	public class TypeIntegerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.joneug.mdal.Mdal.TypeInteger");
		private final Keyword cIntegerKeyword = (Keyword)rule.eContents().get(1);
		
		//TypeInteger:
		//	'Integer';
		@Override public ParserRule getRule() { return rule; }
		
		//'Integer'
		public Keyword getIntegerKeyword() { return cIntegerKeyword; }
	}
	public class TypeBigIntegerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.joneug.mdal.Mdal.TypeBigInteger");
		private final Keyword cBigIntegerKeyword = (Keyword)rule.eContents().get(1);
		
		//TypeBigInteger:
		//	'BigInteger';
		@Override public ParserRule getRule() { return rule; }
		
		//'BigInteger'
		public Keyword getBigIntegerKeyword() { return cBigIntegerKeyword; }
	}
	public class TypeTextElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.joneug.mdal.Mdal.TypeText");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTypeTextAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTextKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftSquareBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cLengthAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cLengthINTTerminalRuleCall_2_1_0 = (RuleCall)cLengthAssignment_2_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		
		//TypeText:
		//	{TypeText} 'Text' ('[' length=INT ']')?;
		@Override public ParserRule getRule() { return rule; }
		
		//{TypeText} 'Text' ('[' length=INT ']')?
		public Group getGroup() { return cGroup; }
		
		//{TypeText}
		public Action getTypeTextAction_0() { return cTypeTextAction_0; }
		
		//'Text'
		public Keyword getTextKeyword_1() { return cTextKeyword_1; }
		
		//('[' length=INT ']')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_2_0() { return cLeftSquareBracketKeyword_2_0; }
		
		//length=INT
		public Assignment getLengthAssignment_2_1() { return cLengthAssignment_2_1; }
		
		//INT
		public RuleCall getLengthINTTerminalRuleCall_2_1_0() { return cLengthINTTerminalRuleCall_2_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_2_2() { return cRightSquareBracketKeyword_2_2; }
	}
	public class IdRangeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.joneug.mdal.Mdal.IdRange");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cMinAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cMinINTTerminalRuleCall_0_0 = (RuleCall)cMinAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cMaxAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cMaxINTTerminalRuleCall_1_1_0 = (RuleCall)cMaxAssignment_1_1.eContents().get(0);
		
		//IdRange:
		//	min=INT ('..' max=INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//min=INT ('..' max=INT)?
		public Group getGroup() { return cGroup; }
		
		//min=INT
		public Assignment getMinAssignment_0() { return cMinAssignment_0; }
		
		//INT
		public RuleCall getMinINTTerminalRuleCall_0_0() { return cMinINTTerminalRuleCall_0_0; }
		
		//('..' max=INT)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'..'
		public Keyword getFullStopFullStopKeyword_1_0() { return cFullStopFullStopKeyword_1_0; }
		
		//max=INT
		public Assignment getMaxAssignment_1_1() { return cMaxAssignment_1_1; }
		
		//INT
		public RuleCall getMaxINTTerminalRuleCall_1_1_0() { return cMaxINTTerminalRuleCall_1_1_0; }
	}
	
	public class BoolElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "de.joneug.mdal.Mdal.Bool");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cTRUEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cTRUETrueKeyword_0_0 = (Keyword)cTRUEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cFALSEEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cFALSEFalseKeyword_1_0 = (Keyword)cFALSEEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum Bool:
		//	TRUE='true' | FALSE='false';
		public EnumRule getRule() { return rule; }
		
		//TRUE='true' | FALSE='false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//TRUE='true'
		public EnumLiteralDeclaration getTRUEEnumLiteralDeclaration_0() { return cTRUEEnumLiteralDeclaration_0; }
		
		//'true'
		public Keyword getTRUETrueKeyword_0_0() { return cTRUETrueKeyword_0_0; }
		
		//FALSE='false'
		public EnumLiteralDeclaration getFALSEEnumLiteralDeclaration_1() { return cFALSEEnumLiteralDeclaration_1; }
		
		//'false'
		public Keyword getFALSEFalseKeyword_1_0() { return cFALSEFalseKeyword_1_0; }
	}
	
	private final ModelElements pModel;
	private final AlExtensionElements pAlExtension;
	private final DocumentElements pDocument;
	private final FieldElements pField;
	private final TypeElements pType;
	private final TypeIntegerElements pTypeInteger;
	private final TypeBigIntegerElements pTypeBigInteger;
	private final TypeTextElements pTypeText;
	private final IdRangeElements pIdRange;
	private final BoolElements eBool;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MdalGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pAlExtension = new AlExtensionElements();
		this.pDocument = new DocumentElements();
		this.pField = new FieldElements();
		this.pType = new TypeElements();
		this.pTypeInteger = new TypeIntegerElements();
		this.pTypeBigInteger = new TypeBigIntegerElements();
		this.pTypeText = new TypeTextElements();
		this.pIdRange = new IdRangeElements();
		this.eBool = new BoolElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.joneug.mdal.Mdal".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	alExtensions+=AlExtension*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//AlExtension:
	//	'extension' name=STRING '{' ('id' id=STRING)? ('idRanges' '[' (idRanges+=IdRange (',' idRanges+=IdRange)*) ']')?
	//	('platform' platform=STRING)? ('publisher' publisher=STRING)? ('version' version=STRING)? ('brief' brief=STRING)?
	//	('description' description=STRING)? ('privacyStatement' privacyStatement=STRING)? ('eula' eula=STRING)? ('help'
	//	help=STRING)? ('url' url=STRING)? ('contextSensitiveHelpUrl' contextSensitiveHelpUrl=STRING)? ('showMyCode'
	//	showMyCode=Bool)? ('runtime' runtime=STRING)?
	//	'}';
	public AlExtensionElements getAlExtensionAccess() {
		return pAlExtension;
	}
	
	public ParserRule getAlExtensionRule() {
		return getAlExtensionAccess().getRule();
	}
	
	//Document:
	//	'document' name=STRING '{'
	//	'}';
	public DocumentElements getDocumentAccess() {
		return pDocument;
	}
	
	public ParserRule getDocumentRule() {
		return getDocumentAccess().getRule();
	}
	
	//Field:
	//	'field' name=STRING '{' ('no' no=INT)? ('description' description=STRING)?
	//	'type' type=Type
	//	'}';
	public FieldElements getFieldAccess() {
		return pField;
	}
	
	public ParserRule getFieldRule() {
		return getFieldAccess().getRule();
	}
	
	//Type:
	//	TypeText;
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//TypeInteger:
	//	'Integer';
	public TypeIntegerElements getTypeIntegerAccess() {
		return pTypeInteger;
	}
	
	public ParserRule getTypeIntegerRule() {
		return getTypeIntegerAccess().getRule();
	}
	
	//TypeBigInteger:
	//	'BigInteger';
	public TypeBigIntegerElements getTypeBigIntegerAccess() {
		return pTypeBigInteger;
	}
	
	public ParserRule getTypeBigIntegerRule() {
		return getTypeBigIntegerAccess().getRule();
	}
	
	//TypeText:
	//	{TypeText} 'Text' ('[' length=INT ']')?;
	public TypeTextElements getTypeTextAccess() {
		return pTypeText;
	}
	
	public ParserRule getTypeTextRule() {
		return getTypeTextAccess().getRule();
	}
	
	//IdRange:
	//	min=INT ('..' max=INT)?;
	public IdRangeElements getIdRangeAccess() {
		return pIdRange;
	}
	
	public ParserRule getIdRangeRule() {
		return getIdRangeAccess().getRule();
	}
	
	//enum Bool:
	//	TRUE='true' | FALSE='false';
	public BoolElements getBoolAccess() {
		return eBool;
	}
	
	public EnumRule getBoolRule() {
		return getBoolAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
