/**
 * generated by Xtext 2.21.0
 */
package de.joneug.mdal.mdal.impl;

import de.joneug.mdal.mdal.AlExtension;
import de.joneug.mdal.mdal.Bool;
import de.joneug.mdal.mdal.IdRange;
import de.joneug.mdal.mdal.MdalPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Al Extension</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.joneug.mdal.mdal.impl.AlExtensionImpl#getName <em>Name</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.impl.AlExtensionImpl#getId <em>Id</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.impl.AlExtensionImpl#getIdRanges <em>Id Ranges</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.impl.AlExtensionImpl#getPlatform <em>Platform</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.impl.AlExtensionImpl#getPublisher <em>Publisher</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.impl.AlExtensionImpl#getVersion <em>Version</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.impl.AlExtensionImpl#getBrief <em>Brief</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.impl.AlExtensionImpl#getDescription <em>Description</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.impl.AlExtensionImpl#getPrivacyStatement <em>Privacy Statement</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.impl.AlExtensionImpl#getEula <em>Eula</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.impl.AlExtensionImpl#getHelp <em>Help</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.impl.AlExtensionImpl#getUrl <em>Url</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.impl.AlExtensionImpl#getContextSensitiveHelpUrl <em>Context Sensitive Help Url</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.impl.AlExtensionImpl#getShowMyCode <em>Show My Code</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.impl.AlExtensionImpl#getRuntime <em>Runtime</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AlExtensionImpl extends MinimalEObjectImpl.Container implements AlExtension
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected static final String ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected String id = ID_EDEFAULT;

  /**
   * The cached value of the '{@link #getIdRanges() <em>Id Ranges</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdRanges()
   * @generated
   * @ordered
   */
  protected EList<IdRange> idRanges;

  /**
   * The default value of the '{@link #getPlatform() <em>Platform</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPlatform()
   * @generated
   * @ordered
   */
  protected static final String PLATFORM_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPlatform() <em>Platform</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPlatform()
   * @generated
   * @ordered
   */
  protected String platform = PLATFORM_EDEFAULT;

  /**
   * The default value of the '{@link #getPublisher() <em>Publisher</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPublisher()
   * @generated
   * @ordered
   */
  protected static final String PUBLISHER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPublisher() <em>Publisher</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPublisher()
   * @generated
   * @ordered
   */
  protected String publisher = PUBLISHER_EDEFAULT;

  /**
   * The default value of the '{@link #getVersion() <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVersion()
   * @generated
   * @ordered
   */
  protected static final String VERSION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVersion() <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVersion()
   * @generated
   * @ordered
   */
  protected String version = VERSION_EDEFAULT;

  /**
   * The default value of the '{@link #getBrief() <em>Brief</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBrief()
   * @generated
   * @ordered
   */
  protected static final String BRIEF_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getBrief() <em>Brief</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBrief()
   * @generated
   * @ordered
   */
  protected String brief = BRIEF_EDEFAULT;

  /**
   * The default value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected static final String DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected String description = DESCRIPTION_EDEFAULT;

  /**
   * The default value of the '{@link #getPrivacyStatement() <em>Privacy Statement</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrivacyStatement()
   * @generated
   * @ordered
   */
  protected static final String PRIVACY_STATEMENT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPrivacyStatement() <em>Privacy Statement</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrivacyStatement()
   * @generated
   * @ordered
   */
  protected String privacyStatement = PRIVACY_STATEMENT_EDEFAULT;

  /**
   * The default value of the '{@link #getEula() <em>Eula</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEula()
   * @generated
   * @ordered
   */
  protected static final String EULA_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEula() <em>Eula</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEula()
   * @generated
   * @ordered
   */
  protected String eula = EULA_EDEFAULT;

  /**
   * The default value of the '{@link #getHelp() <em>Help</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHelp()
   * @generated
   * @ordered
   */
  protected static final String HELP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getHelp() <em>Help</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHelp()
   * @generated
   * @ordered
   */
  protected String help = HELP_EDEFAULT;

  /**
   * The default value of the '{@link #getUrl() <em>Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUrl()
   * @generated
   * @ordered
   */
  protected static final String URL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getUrl() <em>Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUrl()
   * @generated
   * @ordered
   */
  protected String url = URL_EDEFAULT;

  /**
   * The default value of the '{@link #getContextSensitiveHelpUrl() <em>Context Sensitive Help Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContextSensitiveHelpUrl()
   * @generated
   * @ordered
   */
  protected static final String CONTEXT_SENSITIVE_HELP_URL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getContextSensitiveHelpUrl() <em>Context Sensitive Help Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContextSensitiveHelpUrl()
   * @generated
   * @ordered
   */
  protected String contextSensitiveHelpUrl = CONTEXT_SENSITIVE_HELP_URL_EDEFAULT;

  /**
   * The default value of the '{@link #getShowMyCode() <em>Show My Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShowMyCode()
   * @generated
   * @ordered
   */
  protected static final Bool SHOW_MY_CODE_EDEFAULT = Bool.TRUE;

  /**
   * The cached value of the '{@link #getShowMyCode() <em>Show My Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShowMyCode()
   * @generated
   * @ordered
   */
  protected Bool showMyCode = SHOW_MY_CODE_EDEFAULT;

  /**
   * The default value of the '{@link #getRuntime() <em>Runtime</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRuntime()
   * @generated
   * @ordered
   */
  protected static final String RUNTIME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRuntime() <em>Runtime</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRuntime()
   * @generated
   * @ordered
   */
  protected String runtime = RUNTIME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AlExtensionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MdalPackage.Literals.AL_EXTENSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MdalPackage.AL_EXTENSION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getId()
  {
    return id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setId(String newId)
  {
    String oldId = id;
    id = newId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MdalPackage.AL_EXTENSION__ID, oldId, id));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<IdRange> getIdRanges()
  {
    if (idRanges == null)
    {
      idRanges = new EObjectContainmentEList<IdRange>(IdRange.class, this, MdalPackage.AL_EXTENSION__ID_RANGES);
    }
    return idRanges;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPlatform()
  {
    return platform;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPlatform(String newPlatform)
  {
    String oldPlatform = platform;
    platform = newPlatform;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MdalPackage.AL_EXTENSION__PLATFORM, oldPlatform, platform));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPublisher()
  {
    return publisher;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPublisher(String newPublisher)
  {
    String oldPublisher = publisher;
    publisher = newPublisher;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MdalPackage.AL_EXTENSION__PUBLISHER, oldPublisher, publisher));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVersion()
  {
    return version;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVersion(String newVersion)
  {
    String oldVersion = version;
    version = newVersion;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MdalPackage.AL_EXTENSION__VERSION, oldVersion, version));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getBrief()
  {
    return brief;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBrief(String newBrief)
  {
    String oldBrief = brief;
    brief = newBrief;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MdalPackage.AL_EXTENSION__BRIEF, oldBrief, brief));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDescription()
  {
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDescription(String newDescription)
  {
    String oldDescription = description;
    description = newDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MdalPackage.AL_EXTENSION__DESCRIPTION, oldDescription, description));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPrivacyStatement()
  {
    return privacyStatement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPrivacyStatement(String newPrivacyStatement)
  {
    String oldPrivacyStatement = privacyStatement;
    privacyStatement = newPrivacyStatement;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MdalPackage.AL_EXTENSION__PRIVACY_STATEMENT, oldPrivacyStatement, privacyStatement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEula()
  {
    return eula;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEula(String newEula)
  {
    String oldEula = eula;
    eula = newEula;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MdalPackage.AL_EXTENSION__EULA, oldEula, eula));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getHelp()
  {
    return help;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHelp(String newHelp)
  {
    String oldHelp = help;
    help = newHelp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MdalPackage.AL_EXTENSION__HELP, oldHelp, help));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getUrl()
  {
    return url;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUrl(String newUrl)
  {
    String oldUrl = url;
    url = newUrl;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MdalPackage.AL_EXTENSION__URL, oldUrl, url));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getContextSensitiveHelpUrl()
  {
    return contextSensitiveHelpUrl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setContextSensitiveHelpUrl(String newContextSensitiveHelpUrl)
  {
    String oldContextSensitiveHelpUrl = contextSensitiveHelpUrl;
    contextSensitiveHelpUrl = newContextSensitiveHelpUrl;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MdalPackage.AL_EXTENSION__CONTEXT_SENSITIVE_HELP_URL, oldContextSensitiveHelpUrl, contextSensitiveHelpUrl));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Bool getShowMyCode()
  {
    return showMyCode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setShowMyCode(Bool newShowMyCode)
  {
    Bool oldShowMyCode = showMyCode;
    showMyCode = newShowMyCode == null ? SHOW_MY_CODE_EDEFAULT : newShowMyCode;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MdalPackage.AL_EXTENSION__SHOW_MY_CODE, oldShowMyCode, showMyCode));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRuntime()
  {
    return runtime;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRuntime(String newRuntime)
  {
    String oldRuntime = runtime;
    runtime = newRuntime;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MdalPackage.AL_EXTENSION__RUNTIME, oldRuntime, runtime));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MdalPackage.AL_EXTENSION__ID_RANGES:
        return ((InternalEList<?>)getIdRanges()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MdalPackage.AL_EXTENSION__NAME:
        return getName();
      case MdalPackage.AL_EXTENSION__ID:
        return getId();
      case MdalPackage.AL_EXTENSION__ID_RANGES:
        return getIdRanges();
      case MdalPackage.AL_EXTENSION__PLATFORM:
        return getPlatform();
      case MdalPackage.AL_EXTENSION__PUBLISHER:
        return getPublisher();
      case MdalPackage.AL_EXTENSION__VERSION:
        return getVersion();
      case MdalPackage.AL_EXTENSION__BRIEF:
        return getBrief();
      case MdalPackage.AL_EXTENSION__DESCRIPTION:
        return getDescription();
      case MdalPackage.AL_EXTENSION__PRIVACY_STATEMENT:
        return getPrivacyStatement();
      case MdalPackage.AL_EXTENSION__EULA:
        return getEula();
      case MdalPackage.AL_EXTENSION__HELP:
        return getHelp();
      case MdalPackage.AL_EXTENSION__URL:
        return getUrl();
      case MdalPackage.AL_EXTENSION__CONTEXT_SENSITIVE_HELP_URL:
        return getContextSensitiveHelpUrl();
      case MdalPackage.AL_EXTENSION__SHOW_MY_CODE:
        return getShowMyCode();
      case MdalPackage.AL_EXTENSION__RUNTIME:
        return getRuntime();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MdalPackage.AL_EXTENSION__NAME:
        setName((String)newValue);
        return;
      case MdalPackage.AL_EXTENSION__ID:
        setId((String)newValue);
        return;
      case MdalPackage.AL_EXTENSION__ID_RANGES:
        getIdRanges().clear();
        getIdRanges().addAll((Collection<? extends IdRange>)newValue);
        return;
      case MdalPackage.AL_EXTENSION__PLATFORM:
        setPlatform((String)newValue);
        return;
      case MdalPackage.AL_EXTENSION__PUBLISHER:
        setPublisher((String)newValue);
        return;
      case MdalPackage.AL_EXTENSION__VERSION:
        setVersion((String)newValue);
        return;
      case MdalPackage.AL_EXTENSION__BRIEF:
        setBrief((String)newValue);
        return;
      case MdalPackage.AL_EXTENSION__DESCRIPTION:
        setDescription((String)newValue);
        return;
      case MdalPackage.AL_EXTENSION__PRIVACY_STATEMENT:
        setPrivacyStatement((String)newValue);
        return;
      case MdalPackage.AL_EXTENSION__EULA:
        setEula((String)newValue);
        return;
      case MdalPackage.AL_EXTENSION__HELP:
        setHelp((String)newValue);
        return;
      case MdalPackage.AL_EXTENSION__URL:
        setUrl((String)newValue);
        return;
      case MdalPackage.AL_EXTENSION__CONTEXT_SENSITIVE_HELP_URL:
        setContextSensitiveHelpUrl((String)newValue);
        return;
      case MdalPackage.AL_EXTENSION__SHOW_MY_CODE:
        setShowMyCode((Bool)newValue);
        return;
      case MdalPackage.AL_EXTENSION__RUNTIME:
        setRuntime((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MdalPackage.AL_EXTENSION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MdalPackage.AL_EXTENSION__ID:
        setId(ID_EDEFAULT);
        return;
      case MdalPackage.AL_EXTENSION__ID_RANGES:
        getIdRanges().clear();
        return;
      case MdalPackage.AL_EXTENSION__PLATFORM:
        setPlatform(PLATFORM_EDEFAULT);
        return;
      case MdalPackage.AL_EXTENSION__PUBLISHER:
        setPublisher(PUBLISHER_EDEFAULT);
        return;
      case MdalPackage.AL_EXTENSION__VERSION:
        setVersion(VERSION_EDEFAULT);
        return;
      case MdalPackage.AL_EXTENSION__BRIEF:
        setBrief(BRIEF_EDEFAULT);
        return;
      case MdalPackage.AL_EXTENSION__DESCRIPTION:
        setDescription(DESCRIPTION_EDEFAULT);
        return;
      case MdalPackage.AL_EXTENSION__PRIVACY_STATEMENT:
        setPrivacyStatement(PRIVACY_STATEMENT_EDEFAULT);
        return;
      case MdalPackage.AL_EXTENSION__EULA:
        setEula(EULA_EDEFAULT);
        return;
      case MdalPackage.AL_EXTENSION__HELP:
        setHelp(HELP_EDEFAULT);
        return;
      case MdalPackage.AL_EXTENSION__URL:
        setUrl(URL_EDEFAULT);
        return;
      case MdalPackage.AL_EXTENSION__CONTEXT_SENSITIVE_HELP_URL:
        setContextSensitiveHelpUrl(CONTEXT_SENSITIVE_HELP_URL_EDEFAULT);
        return;
      case MdalPackage.AL_EXTENSION__SHOW_MY_CODE:
        setShowMyCode(SHOW_MY_CODE_EDEFAULT);
        return;
      case MdalPackage.AL_EXTENSION__RUNTIME:
        setRuntime(RUNTIME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MdalPackage.AL_EXTENSION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MdalPackage.AL_EXTENSION__ID:
        return ID_EDEFAULT == null ? id != null : !ID_EDEFAULT.equals(id);
      case MdalPackage.AL_EXTENSION__ID_RANGES:
        return idRanges != null && !idRanges.isEmpty();
      case MdalPackage.AL_EXTENSION__PLATFORM:
        return PLATFORM_EDEFAULT == null ? platform != null : !PLATFORM_EDEFAULT.equals(platform);
      case MdalPackage.AL_EXTENSION__PUBLISHER:
        return PUBLISHER_EDEFAULT == null ? publisher != null : !PUBLISHER_EDEFAULT.equals(publisher);
      case MdalPackage.AL_EXTENSION__VERSION:
        return VERSION_EDEFAULT == null ? version != null : !VERSION_EDEFAULT.equals(version);
      case MdalPackage.AL_EXTENSION__BRIEF:
        return BRIEF_EDEFAULT == null ? brief != null : !BRIEF_EDEFAULT.equals(brief);
      case MdalPackage.AL_EXTENSION__DESCRIPTION:
        return DESCRIPTION_EDEFAULT == null ? description != null : !DESCRIPTION_EDEFAULT.equals(description);
      case MdalPackage.AL_EXTENSION__PRIVACY_STATEMENT:
        return PRIVACY_STATEMENT_EDEFAULT == null ? privacyStatement != null : !PRIVACY_STATEMENT_EDEFAULT.equals(privacyStatement);
      case MdalPackage.AL_EXTENSION__EULA:
        return EULA_EDEFAULT == null ? eula != null : !EULA_EDEFAULT.equals(eula);
      case MdalPackage.AL_EXTENSION__HELP:
        return HELP_EDEFAULT == null ? help != null : !HELP_EDEFAULT.equals(help);
      case MdalPackage.AL_EXTENSION__URL:
        return URL_EDEFAULT == null ? url != null : !URL_EDEFAULT.equals(url);
      case MdalPackage.AL_EXTENSION__CONTEXT_SENSITIVE_HELP_URL:
        return CONTEXT_SENSITIVE_HELP_URL_EDEFAULT == null ? contextSensitiveHelpUrl != null : !CONTEXT_SENSITIVE_HELP_URL_EDEFAULT.equals(contextSensitiveHelpUrl);
      case MdalPackage.AL_EXTENSION__SHOW_MY_CODE:
        return showMyCode != SHOW_MY_CODE_EDEFAULT;
      case MdalPackage.AL_EXTENSION__RUNTIME:
        return RUNTIME_EDEFAULT == null ? runtime != null : !RUNTIME_EDEFAULT.equals(runtime);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", id: ");
    result.append(id);
    result.append(", platform: ");
    result.append(platform);
    result.append(", publisher: ");
    result.append(publisher);
    result.append(", version: ");
    result.append(version);
    result.append(", brief: ");
    result.append(brief);
    result.append(", description: ");
    result.append(description);
    result.append(", privacyStatement: ");
    result.append(privacyStatement);
    result.append(", eula: ");
    result.append(eula);
    result.append(", help: ");
    result.append(help);
    result.append(", url: ");
    result.append(url);
    result.append(", contextSensitiveHelpUrl: ");
    result.append(contextSensitiveHelpUrl);
    result.append(", showMyCode: ");
    result.append(showMyCode);
    result.append(", runtime: ");
    result.append(runtime);
    result.append(')');
    return result.toString();
  }

} //AlExtensionImpl
