/*
 * generated by Xtext 2.21.0
 */
package de.joneug.ide

import com.google.inject.Guice
import de.joneug.MdalRuntimeModule
import de.joneug.MdalStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MdalIdeSetup extends MdalStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MdalRuntimeModule, new MdalIdeModule))
	}
	
}
