/**
 * generated by Xtext 2.21.0
 */
package de.joneug.mdal.mdal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Al Extension</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.joneug.mdal.mdal.AlExtension#getName <em>Name</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.AlExtension#getId <em>Id</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.AlExtension#getIdRanges <em>Id Ranges</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.AlExtension#getPlatform <em>Platform</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.AlExtension#getPublisher <em>Publisher</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.AlExtension#getVersion <em>Version</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.AlExtension#getBrief <em>Brief</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.AlExtension#getDescription <em>Description</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.AlExtension#getPrivacyStatement <em>Privacy Statement</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.AlExtension#getEula <em>Eula</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.AlExtension#getHelp <em>Help</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.AlExtension#getUrl <em>Url</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.AlExtension#getContextSensitiveHelpUrl <em>Context Sensitive Help Url</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.AlExtension#getShowMyCode <em>Show My Code</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.AlExtension#getRuntime <em>Runtime</em>}</li>
 * </ul>
 *
 * @see de.joneug.mdal.mdal.MdalPackage#getAlExtension()
 * @model
 * @generated
 */
public interface AlExtension extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.joneug.mdal.mdal.MdalPackage#getAlExtension_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.joneug.mdal.mdal.AlExtension#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see de.joneug.mdal.mdal.MdalPackage#getAlExtension_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link de.joneug.mdal.mdal.AlExtension#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Id Ranges</b></em>' containment reference list.
   * The list contents are of type {@link de.joneug.mdal.mdal.IdRange}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id Ranges</em>' containment reference list.
   * @see de.joneug.mdal.mdal.MdalPackage#getAlExtension_IdRanges()
   * @model containment="true"
   * @generated
   */
  EList<IdRange> getIdRanges();

  /**
   * Returns the value of the '<em><b>Platform</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Platform</em>' attribute.
   * @see #setPlatform(String)
   * @see de.joneug.mdal.mdal.MdalPackage#getAlExtension_Platform()
   * @model
   * @generated
   */
  String getPlatform();

  /**
   * Sets the value of the '{@link de.joneug.mdal.mdal.AlExtension#getPlatform <em>Platform</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Platform</em>' attribute.
   * @see #getPlatform()
   * @generated
   */
  void setPlatform(String value);

  /**
   * Returns the value of the '<em><b>Publisher</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Publisher</em>' attribute.
   * @see #setPublisher(String)
   * @see de.joneug.mdal.mdal.MdalPackage#getAlExtension_Publisher()
   * @model
   * @generated
   */
  String getPublisher();

  /**
   * Sets the value of the '{@link de.joneug.mdal.mdal.AlExtension#getPublisher <em>Publisher</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Publisher</em>' attribute.
   * @see #getPublisher()
   * @generated
   */
  void setPublisher(String value);

  /**
   * Returns the value of the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Version</em>' attribute.
   * @see #setVersion(String)
   * @see de.joneug.mdal.mdal.MdalPackage#getAlExtension_Version()
   * @model
   * @generated
   */
  String getVersion();

  /**
   * Sets the value of the '{@link de.joneug.mdal.mdal.AlExtension#getVersion <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Version</em>' attribute.
   * @see #getVersion()
   * @generated
   */
  void setVersion(String value);

  /**
   * Returns the value of the '<em><b>Brief</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Brief</em>' attribute.
   * @see #setBrief(String)
   * @see de.joneug.mdal.mdal.MdalPackage#getAlExtension_Brief()
   * @model
   * @generated
   */
  String getBrief();

  /**
   * Sets the value of the '{@link de.joneug.mdal.mdal.AlExtension#getBrief <em>Brief</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Brief</em>' attribute.
   * @see #getBrief()
   * @generated
   */
  void setBrief(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see de.joneug.mdal.mdal.MdalPackage#getAlExtension_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link de.joneug.mdal.mdal.AlExtension#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Privacy Statement</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Privacy Statement</em>' attribute.
   * @see #setPrivacyStatement(String)
   * @see de.joneug.mdal.mdal.MdalPackage#getAlExtension_PrivacyStatement()
   * @model
   * @generated
   */
  String getPrivacyStatement();

  /**
   * Sets the value of the '{@link de.joneug.mdal.mdal.AlExtension#getPrivacyStatement <em>Privacy Statement</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Privacy Statement</em>' attribute.
   * @see #getPrivacyStatement()
   * @generated
   */
  void setPrivacyStatement(String value);

  /**
   * Returns the value of the '<em><b>Eula</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Eula</em>' attribute.
   * @see #setEula(String)
   * @see de.joneug.mdal.mdal.MdalPackage#getAlExtension_Eula()
   * @model
   * @generated
   */
  String getEula();

  /**
   * Sets the value of the '{@link de.joneug.mdal.mdal.AlExtension#getEula <em>Eula</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Eula</em>' attribute.
   * @see #getEula()
   * @generated
   */
  void setEula(String value);

  /**
   * Returns the value of the '<em><b>Help</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Help</em>' attribute.
   * @see #setHelp(String)
   * @see de.joneug.mdal.mdal.MdalPackage#getAlExtension_Help()
   * @model
   * @generated
   */
  String getHelp();

  /**
   * Sets the value of the '{@link de.joneug.mdal.mdal.AlExtension#getHelp <em>Help</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Help</em>' attribute.
   * @see #getHelp()
   * @generated
   */
  void setHelp(String value);

  /**
   * Returns the value of the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Url</em>' attribute.
   * @see #setUrl(String)
   * @see de.joneug.mdal.mdal.MdalPackage#getAlExtension_Url()
   * @model
   * @generated
   */
  String getUrl();

  /**
   * Sets the value of the '{@link de.joneug.mdal.mdal.AlExtension#getUrl <em>Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Url</em>' attribute.
   * @see #getUrl()
   * @generated
   */
  void setUrl(String value);

  /**
   * Returns the value of the '<em><b>Context Sensitive Help Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Context Sensitive Help Url</em>' attribute.
   * @see #setContextSensitiveHelpUrl(String)
   * @see de.joneug.mdal.mdal.MdalPackage#getAlExtension_ContextSensitiveHelpUrl()
   * @model
   * @generated
   */
  String getContextSensitiveHelpUrl();

  /**
   * Sets the value of the '{@link de.joneug.mdal.mdal.AlExtension#getContextSensitiveHelpUrl <em>Context Sensitive Help Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Context Sensitive Help Url</em>' attribute.
   * @see #getContextSensitiveHelpUrl()
   * @generated
   */
  void setContextSensitiveHelpUrl(String value);

  /**
   * Returns the value of the '<em><b>Show My Code</b></em>' attribute.
   * The literals are from the enumeration {@link de.joneug.mdal.mdal.Bool}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Show My Code</em>' attribute.
   * @see de.joneug.mdal.mdal.Bool
   * @see #setShowMyCode(Bool)
   * @see de.joneug.mdal.mdal.MdalPackage#getAlExtension_ShowMyCode()
   * @model
   * @generated
   */
  Bool getShowMyCode();

  /**
   * Sets the value of the '{@link de.joneug.mdal.mdal.AlExtension#getShowMyCode <em>Show My Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Show My Code</em>' attribute.
   * @see de.joneug.mdal.mdal.Bool
   * @see #getShowMyCode()
   * @generated
   */
  void setShowMyCode(Bool value);

  /**
   * Returns the value of the '<em><b>Runtime</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Runtime</em>' attribute.
   * @see #setRuntime(String)
   * @see de.joneug.mdal.mdal.MdalPackage#getAlExtension_Runtime()
   * @model
   * @generated
   */
  String getRuntime();

  /**
   * Sets the value of the '{@link de.joneug.mdal.mdal.AlExtension#getRuntime <em>Runtime</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Runtime</em>' attribute.
   * @see #getRuntime()
   * @generated
   */
  void setRuntime(String value);

} // AlExtension
