/**
 * generated by Xtext 2.21.0
 */
package de.joneug.mdal.mdal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Id Range</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.joneug.mdal.mdal.IdRange#getMin <em>Min</em>}</li>
 *   <li>{@link de.joneug.mdal.mdal.IdRange#getMax <em>Max</em>}</li>
 * </ul>
 *
 * @see de.joneug.mdal.mdal.MdalPackage#getIdRange()
 * @model
 * @generated
 */
public interface IdRange extends EObject
{
  /**
   * Returns the value of the '<em><b>Min</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Min</em>' attribute.
   * @see #setMin(int)
   * @see de.joneug.mdal.mdal.MdalPackage#getIdRange_Min()
   * @model
   * @generated
   */
  int getMin();

  /**
   * Sets the value of the '{@link de.joneug.mdal.mdal.IdRange#getMin <em>Min</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Min</em>' attribute.
   * @see #getMin()
   * @generated
   */
  void setMin(int value);

  /**
   * Returns the value of the '<em><b>Max</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max</em>' attribute.
   * @see #setMax(int)
   * @see de.joneug.mdal.mdal.MdalPackage#getIdRange_Max()
   * @model
   * @generated
   */
  int getMax();

  /**
   * Sets the value of the '{@link de.joneug.mdal.mdal.IdRange#getMax <em>Max</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max</em>' attribute.
   * @see #getMax()
   * @generated
   */
  void setMax(int value);

} // IdRange
