/**
 * generated by Xtext 2.21.0
 */
package de.joneug.mdal.mdal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.joneug.mdal.mdal.Model#getAlExtensions <em>Al Extensions</em>}</li>
 * </ul>
 *
 * @see de.joneug.mdal.mdal.MdalPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Al Extensions</b></em>' containment reference list.
   * The list contents are of type {@link de.joneug.mdal.mdal.AlExtension}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Al Extensions</em>' containment reference list.
   * @see de.joneug.mdal.mdal.MdalPackage#getModel_AlExtensions()
   * @model containment="true"
   * @generated
   */
  EList<AlExtension> getAlExtensions();

} // Model
