/**
 * generated by Xtext 2.21.0
 */
package de.joneug.mdal.mdal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Text</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.joneug.mdal.mdal.TypeText#getLength <em>Length</em>}</li>
 * </ul>
 *
 * @see de.joneug.mdal.mdal.MdalPackage#getTypeText()
 * @model
 * @generated
 */
public interface TypeText extends Type
{
  /**
   * Returns the value of the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Length</em>' attribute.
   * @see #setLength(int)
   * @see de.joneug.mdal.mdal.MdalPackage#getTypeText_Length()
   * @model
   * @generated
   */
  int getLength();

  /**
   * Sets the value of the '{@link de.joneug.mdal.mdal.TypeText#getLength <em>Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Length</em>' attribute.
   * @see #getLength()
   * @generated
   */
  void setLength(int value);

} // TypeText
