/**
 * generated by Xtext 2.21.0
 */
package de.joneug.mdal.mdal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.joneug.mdal.mdal.MdalPackage#getType()
 * @model
 * @generated
 */
public interface Type extends EObject
{
} // Type
