/*
 * generated by Xtext 2.21.0
 */
package de.joneug


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MdalStandaloneSetup extends MdalStandaloneSetupGenerated {

	def static void doSetup() {
		new MdalStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
